Fix NoSuchMethodError in ProblemResponseErrorHandler (#165)
Same compatibility error as #98, but this time for
ProblemResponseErrorHandler (used for RestTemplate and RestClient)
instead of WebClient.

Moves ProblemResponseErrorHandler and ProblemRestTemplateCustomizer to
version-specific spring-boot submodules.

I was able to test this fix in another project successfully

---------

Co-authored-by: Jimmy Praet <jimmy.praet@ksz-bcss.fgov.be>