Upgrade to Spring Boot 3.3.4 and fix NoSuchMethodError (#108)
The NoSuchMethodError was introduced in #107 for Spring Boot 3:

```
 2024-09-27 12:26:54,116 [http-nio-auto-1-exec-10] W o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver doResolveHandlerMethodException - Failure in @ExceptionHandler io.github.belgif.rest.problem.spring.RoutingExceptionsHandler#handleHttpMediaTypeNotSupported(HttpMediaTypeNotSupportedException)
java.lang.NoSuchMethodError: 'org.springframework.http.ResponseEntity$BodyBuilder org.springframework.http.ResponseEntity.status(org.springframework.http.HttpStatus)'
```

The reason for the NoSuchMethodError is that
org.springframework.http.ResponseEntity.status(org.springframework.http.HttpStatus)
changed to
org.springframework.http.ResponseEntity.status(org.springframework.http.HttpStatusCode)
in Spring 6 (similar to #98).

It went unnoticed because when an ExceptionHandler throws an exception,
there is a fallback to
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.html
which already maps these exceptions to the correct HTTP status code. I
just accidentally noticed the warning in the logs when running a local
build.